[tool.poetry]
name = "gtfs-extractor"
version = "0.1.0"
description = ""
authors = ["Julian Psotta <julianpsotta@gmail.com>"]
readme = "README.md"
packages = [{ include = "gtfs_extractor" }]

[tool.poetry.dependencies]
python = ">=3.8,<4"
dask = "^2022.9.2"
pandas = "^1.5.0"
typer = "^0.6.1"
rich = "^12.6.0"



[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.8.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.982"
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 121
skip_glob = ["**/.env*", "**/.venv*", "**/env/*", "**/.venv/*", "**/docs/*"]

[tool.black]
line-length = 121
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.coverage
  | \.tox
  | \.venv
  | \.env
  | \.venv310
  | \.venv309
  | \.venv308
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
log_cli = true
log_cli_level = 30 # Warnings
